### ISSUE TITLE
Error 0xc0000005

### ISSUE THREAD

**Issue by guncu666** [R2Northstar/Northstar#65] opened 2021-12-27 15:57 UTC
report"0xc0000005"when I first start the NorthstarLauncher. What happen?

**Comment by 334431** [comment] 2021-12-27 17:31
Try verifying files through steam or origin, if that does not work try reinstalling Northstar

**Comment by SeriousGous** [comment] 2021-12-27 20:27
> report"0xc0000005"when I first start the NorthstarLauncher. What happen?

Guessing you on windows 7 x64 too?
The problem seems unsolvable, the only thing I haven't tried yet is to reinstall Microsoft Redistributables

**Comment by guncu666** [comment] 2021-12-28 09:42
maybe find the problem, but don't know how to fix it
the crash data have mention the Microsoft .NET Framework1.1 but I already uninstall it. Does anyone know how to fix it?

**Comment by AnonPilot35** [comment] 2021-12-29 02:05
> Guessing you on windows 7 x64 too?

Confirmed on Windows 11 x64, as well.

>Try verifying files through steam or origin, if that does not work try reinstalling Northstar

I tried this, but this did not fix the issue.

**Comment by shanzenos** [comment] 2021-12-30 00:09
Can confirm after testing it myself. I'm assuming one of the dependencies is using some framework that's not compatible with other windows OS's besides 10. The modified "unpacked" application and launcher don't seem to work correctly on windows 7, 8 or 11 (tested) I also have all my redists on each fully updated. 

All produce the "error 0xc0000005" and setting the modified game client application to run in compatibility mode for anything causes a different error from the launcher "check if bob shipped a debug build by accident".

**Comment by barnabwhy** [comment] 2021-12-30 00:14
This is not strictly true, I got the server to work on Windows Server 2012 R2 (nice name similarity) just fine and that’s based on win8

**Comment by Juesto** [comment] 2021-12-30 04:11
the solution is unfortunately disabling ASLR.
the alternative to this is injecting northstar.dll manually into titanfall2.exe before the game window comes up.

**Comment by Freddycat** [comment] 2021-12-30 18:12
Disabling ASLR is not working for me , how do you inject manually?

**Comment by SeriousGous** [comment] 2021-12-30 18:52
> the solution is unfortunately disabling ASLR. the alternative to this is injecting northstar.dll manually into titanfall2.exe before the game window comes up.

Thank you endlessly, injecting is a bit tricky since you have to do it very fast, before the window shows up, but it actually worked for me on win 7 x64!

**Comment by Juesto** [comment] 2021-12-30 19:02
> > the solution is unfortunately disabling ASLR. the alternative to this is injecting northstar.dll manually into titanfall2.exe before the game window comes up.
> 
> Thank you endlessly, injecting is a bit tricky since you have to do it very fast, before the window shows up, but it actually worked for me on win 7 x64!

the injection window is between a very small moment after process spawn and game window coming up, for both dedicated and game, since you're running vanilla through launcher this prevents multiple instances and therefore running dedicated and the game at once.

this bypasses #81 as well

**Comment by guncu666** [comment] 2021-12-31 16:55
" injecting northstar.dll manually into titanfall2.exe before the game window comes up."
How can I do it??

**Comment by Juesto** [comment] 2021-12-31 19:20
> " injecting northstar.dll manually into titanfall2.exe before the game window comes up." How can I do it??

get extreme injector, select titanfall2 process with the game running, close it, drag northstar.dll into the list. run titanfall 2 normally and inject before the game window comes up, should work. this is a workaround mind you, every time you want northstar you need to do the same thing for now. a fix is being worked on

**Comment by manotroll** [comment] 2021-12-31 23:23
https://i.imgur.com/Zl8p0zA.png
win11 21H2 22000.376

**Comment by GeckoEidechse** [comment] 2022-01-01 13:28
> The modified "unpacked" application and launcher don't seem to work correctly on windows 7, 8 or 11 (tested) I also have all my redists on each fully updated.

Not strictly true for 8. I'm (one of the few maniacs still) running Windows 8.1 and I never experienced that error.

**Comment by Juesto** [comment] 2022-01-01 18:14
> > The modified "unpacked" application and launcher don't seem to work correctly on windows 7, 8 or 11 (tested) I also have all my redists on each fully updated.
> 
> Not strictly true for 8. I'm (one of the few maniacs still) running Windows 8.1 and I never experienced that error.

regardless, the exe is a dump not something proper, this is getting ditched in favor of a better launcher see p0358 pr and discord thread

**Comment by manotroll** [comment] 2022-01-01 19:57
So is a better alternative coming?

**Comment by GeckoEidechse** [comment] 2022-01-01 20:01
@manotroll, it's still WIP, watch [this pull request](https://github.com/R2Northstar/NorthstarLauncher/pull/19) if you're curious.

**Comment by p0358** [comment] 2022-01-06 05:28
Should be completely fixed in v1.4.0 now

**Comment by abarichello** [comment] 2022-01-07 12:35
Let us know if it happens on newer releases

**Closed** 2022-01-07 12:35 UTC
Labels: bug
