### ISSUE TITLE
Grapple is broke

### ISSUE THREAD

**Issue by Zayveeo5e** [R2Northstar/Northstar#255] opened 2022-04-14 14:23 UTC
### Bug
Grapple is buggy and sometimes crashes

### Steps to reproduce

  1. Start/Join a match
  2. Grapple a pilot
  3. Crash or, if you're lucky, lose an entire grapple charge instantly without other person moving

### Specifications
  - Northstar version: 1.6.3
  - Platform: Origin

**Comment by GeckoEidechse** [comment] 2022-04-14 22:51
Can't check right now but if anyone else can reproduce it, please LMK.

**Comment by Dinorush** [comment] 2022-04-15 09:31
Can't check crash, but losing an entire grapple charge when grappling entities is vanilla behavior.

**Comment by ASpoonPlaysGames** [comment] 2022-05-05 13:50
yeah so this is still a problem in latest build, very weird behaviour where you will grapple someone, and then appear to spam melee like 10 times per second until the grapple breaks or you die, can lead to disconnects due to net chan processing limit sometimes

**Comment by GeckoEidechse** [comment] 2022-07-04 23:56
Should be fixed with `v1.9.0` with https://github.com/R2Northstar/NorthstarLauncher/pull/203. If not, please re-open or make a new issue referencing this one.

**Closed by GeckoEidechse** 2022-07-04 23:56 UTC
Labels: bug
