### ISSUE TITLE
Crash after titanfall in defeat screen

### ISSUE THREAD

**Issue by michardy** [R2Northstar/Northstar#215] opened 2022-03-13 05:46 UTC
### Bug
I was given the option to titanfall in the defeat screen.  I used it and the server promptly crashed.  I also got a weird visual glitch on the client end where my titan spawned a smaller titan that moved and the camera remained top down.  There is a possibility that the bug is mod related although I think it is unlikely

### Steps to reproduce

  1. Disable epilogue and start server
  2. If given the option to titanfall in a end game screen hit enter
  3. Server may crash

### Specifications
  - Northstar version: 1.5.1? (I used this: ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0)
  - Platform: Steam
  - Server OS: Linux 5.13.0-1012-gcp (x86-64)
  - Client OS: Windows 10 19041.1415 (x86-64)
  - Mods: rcon, adminabuse, randomiser, autobalence

```
[05:02:44] [info] [SERVER SPEW_WARNING] Client 'unnervingeye' dropped 2 packets to us
[05:02:44] [info] [SERVER SCRIPT] [AUTOBALANCE] Teams are balanced (IMC: 7, MILITIA: 8)
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] AttackerShouldTriggerReplay(): Not doing a replay by default.
[05:02:44] [info] [SERVER SCRIPT] Post impact,anim is done
[05:02:44] [info] [SERVER SPEW_MESSAGE] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
[05:02:44] [info] [SERVER SPEW_MESSAGE] Setting player "player bushmouse [1]" predicted first person proxy model to "" (class "spectator")
[05:02:44] [info] [SERVER SCRIPT] pilot primary skin/camo 0 0
[05:02:44] [info] [SERVER SCRIPT] pilot secondary skin/camo 0 0
[05:02:44] [info] [SERVER SCRIPT] pilot weapon3 skin/camo 0 0
[05:02:44] [info] [SERVER SPEW_MESSAGE] Setting player "player bushmouse [1]" predicted first person proxy model to "models/weapons/arms/pov_pilot_medium_geist_m.mdl" (class "pilot_grapple_male")
[05:02:44] [info] [SERVER SCRIPT] pilot primary skin/camo 0 0
[05:02:44] [info] [SERVER SCRIPT] pilot secondary skin/camo 0 0
[05:02:44] [info] [SERVER SCRIPT] pilot weapon3 skin/camo 0 0
[05:02:44] [info] [SERVER SCRIPT] 0 -1
[05:02:44] [info] [SERVER SPEW_MESSAGE] Setting player "player bushmouse [1]" predicted first person proxy model to "models/weapons/arms/pov_titan_medium_vanguard.mdl" (class "titan_atlas_vanguard")
[05:02:44] [info] changing mod search path from z:\tmp\ns2491921241\R2Northstar\mods\Northstar.CustomServers\mod to R2Northstar/mods\Northstar.Custom
[05:02:44] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] SetParent: Child prop_dynamic (prop_dynamic [179]) is marked for deletion
[05:02:44] [info] [SERVER SCRIPT]  -> batteryContainer.SetParent( titan, "RODEO_BATTERY" ) //Needed to fix battery being parented to wrong spot after picking a different titan loadout in grace period.
[05:02:44] [info] [SERVER SCRIPT]
CALLSTACK
*FUNCTION [UpdateTitanPanel()] titan/sh_titan.gnut line [208]
*FUNCTION [CPlayer()] class/CPlayer.nut line [327]
*FUNCTION [CPlayer()] class/CPlayer.nut line [306]
*FUNCTION [PilotBecomesTitan()] mp/_titan_transfer.nut line [582]
*FUNCTION [RespawnAsTitan()] mp/_base_gametype_mp.gnut line [491]

[05:02:44] [info] [SERVER SPEW_WARNING] point_viewcontrol point_viewcontrol [246] called Disable when it wasn't the players active view entity.
[05:02:44] [error] Northstar has crashed! a minidump has been written and exception info is available below:
[05:02:44] [error] Cause: Access Violation
Attempted to read from: 0x00000000
[05:02:44] [error] At: engine.dll + 0x247d3a
[05:02:44] [error]     Northstar.dll + 0x128ea47a
[05:02:44] [error]     ntdll.dll + 0x17002567d
[05:02:44] [error]     ntdll.dll + 0x1700548c5
[05:02:44] [error]     ntdll.dll + 0x17005245e
[05:02:44] [error]     engine.dll + 0x19617d3a
[05:02:44] [error]     engine.dll + 0x197e7466
[05:02:44] [error]     engine.dll + 0x194f0c2f
[05:02:44] [error]     engine.dll + 0x194f0542
[05:02:44] [error]     engine.dll + 0x1953db55
[05:02:44] [error]     engine.dll + 0x195988c0
[05:02:44] [error]     Northstar.dll + 0x128d96d6
[05:02:44] [error]     engine.dll + 0x1959652f
[05:02:44] [error]     engine.dll + 0x19760e2d
[05:02:44] [error]     engine.dll + 0x195979d9
[05:02:44] [error]     engine.dll + 0x1959793c
[05:02:44] [error]     launcher.dll + 0x12b05afd
[05:02:44] [error]     launcher.dll + 0x12b05afd
[05:02:44] [error]     launcher.dll + 0x12afd386
[05:02:44] [error]     NorthstarLauncher.exe + 0x140003e7d
[05:02:44] [error]     NorthstarLauncher.exe + 0x140007000
[05:02:44] [error]     kernel32.dll + 0x7b62c599
[05:02:44] [error]     ntdll.dll + 0x170059d53
[05:02:44] [error]     NorthstarLauncher.exe + 0x0
[05:02:44] [error]     NorthstarLauncher.exe + 0x140007070
[05:02:44] [error]     NorthstarLauncher.exe + 0x67ff0000
[05:02:44] [error]     NorthstarLauncher.exe + 0x0
[05:02:44] [error] RAX: 0x0
[05:02:44] [error] RBX: 0x19bb56d0
[05:02:44] [error] RCX: 0x0
[05:02:44] [error] RDX: 0x0
[05:02:44] [error] RSI: 0x2c4abb78
[05:02:44] [error] RDI: 0x2c4abb78
[05:02:44] [error] RBP: 0x2c4abd88
[05:02:44] [error] RSP: 0x7cf470
[05:02:44] [error] R8: 0x2c4abb78
[05:02:44] [error] R9: 0x65
[05:02:44] [error] R10: 0x2c4abd94
[05:02:44] [error] R11: 0x199d78ec
[05:02:44] [error] R12: 0x0
[05:02:44] [error] R13: 0x0
[05:02:44] [error] R14: 0xffffffff
[05:02:44] [error] R15: 0x1
0024:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
0024:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpScanMemory
Error: Failed to run server: server exited: exit status 100.
```

**Comment by RomeoCantCode** [comment] 2022-03-13 09:29
Duplicate and wrong repo.
In NorthstarMods repo there's already an issue regarding that. Also I have a potential fix for that. I sent you a dm on Discord. 
Can you close this and add a comment on issue 227 / NorthstarMods?

**Comment by GeckoEidechse** [comment] 2022-03-13 11:48
> issue 227 / NorthstarMods

I think you made a typo in the referenced issue number, @RomeoCantCode. At least https://github.com/R2Northstar/NorthstarMods/issues/227 looks unrelated to me ^^

**Comment by RomeoCantCode** [comment] 2022-03-13 12:04
https://github.com/R2Northstar/NorthstarMods/issues/231
231 yes  😄

**Comment by GeckoEidechse** [comment] 2022-03-13 12:41
Closing as duplicate of https://github.com/R2Northstar/NorthstarMods/issues/231

@michardy please add a comment to that thread <3

**Closed by GeckoEidechse** 2022-03-13 12:41 UTC
