### ISSUE TITLE
Failed to load launcher DLL

### ISSUE THREAD

**Issue by webuyanycar4** [R2Northstar/Northstar#19] opened 2021-12-24 20:02 UTC
When I try to launch NorthstarLauncher, it gives me an error that says "Failed to load launcher DLL"

**Comment by IncPlusPlus** [comment] 2021-12-24 20:07
Could you provide a screenshot?

**Comment by webuyanycar4** [comment] 2021-12-24 20:10
![Capture](https://user-images.githubusercontent.com/96634376/147371181-ea6dbe8f-e976-49af-8244-a320e2c0f2eb.PNG)
Here

**Comment by IncPlusPlus** [comment] 2021-12-24 20:12
Instead of putting the `custom server stuff` folder itself inside your Titanfall2 folder, put the _**contents of the custom stuff folder**_ inside your Titanfall2 folder.

**Comment by webuyanycar4** [comment] 2021-12-24 20:14
Worked like a charm, thanks

**Comment by IncPlusPlus** [comment] 2021-12-24 20:15
Glad to have helped! Please close this issue if the problem is solved. Have fun!

**Closed** 2022-01-06 10:50 UTC
