### ISSUE TITLE
"Engine Error: File corruption detected. Please repair or re-install the game"

### ISSUE THREAD

**Issue by VITALISED** [R2Northstar/Northstar#6] opened 2021-12-24 09:13 UTC
Should really fix clients on steam who get the following error:
![image](https://user-images.githubusercontent.com/39478251/147338706-74797220-7d7f-4c81-9ba0-d88e29a2a1e2.png)

**Comment by SleepDaemon** [comment] 2021-12-24 09:28
I solve the problem by simply running it as admin. Just right click on the .exe or create a shortcut and right click on that, then properties>advanced>tick _run as adminstrator_>click ok>then apply and then run the game

![image](https://user-images.githubusercontent.com/88533953/147340019-db65dde6-08df-4b8f-930e-816c48115dd6.png)

**Comment by VITALISED** [comment] 2021-12-24 09:42
This doesn't seem to be consistent for everyone however. Different weird voodoo magic tricks seem to work for different steam players

**Comment by GeckoEidechse** [comment] 2021-12-24 11:12
Every time I got this error it was fixed by either restarting Origin, restarting my PC, or launching Northstar with Origin (not yet) started.
This is an Origin error. 

(I own both the Steam and Origin version of Titanfall 2 and when launching Northstar I use the Steam one)

**Comment by FrankenBobbo** [comment] 2021-12-24 11:16
This was the fix that I found after a bit of troubleshooting

- Verify integrity of game files
- Launch the game normally through Steam
- Close the game
- Launch NorthstarLauncher.exe

And it should be working fine

**Comment by VITALISED** [comment] 2021-12-24 12:28
> Every time I got this error it was fixed by either restarting Origin, restarting my PC, or launching Northstar with Origin (not yet) started. This is an Origin error.
> 
> (I own both the Steam and Origin version of Titanfall 2 and when launching Northstar I use the Steam one)

I thought Origin stuff was patched, I'll update issue

**Comment by torodesu** [comment] 2021-12-24 12:34
Same error on the EA Desktop app. None of the solutions above seem to work.

**Comment by GeckoEidechse** [comment] 2021-12-24 12:44
@torodesu have you already tried restarting EA desktop?
AFAIK no testing was done on the EA desktop app before release, so this might need to be tracked on a new issue.

In the meantime, maybe try the steps described [in this troubleshooting page](https://github.com/GeckoEidechse/Northstar-wiki/wiki/Troubleshooting) I'm working on atm.

**Comment by VITALISED** [comment] 2021-12-24 12:45
@torodesu A lot of the solutions so far seem to be incredibly inconsistent between different people. So don't worry, if you do find anything though please add it!

**Comment by torodesu** [comment] 2021-12-24 12:47
> @torodesu have you already tried restarting EA desktop? AFAIK no testing was done on the EA desktop app before release, so this might need to be tracked on a new issue.


I've tried restarting to no avail. None of the solutions on the troubleshooting page seem to work either. 


> @torodesu A lot of the solutions so far seem to be incredibly inconsistent between different people. So don't worry, if you do find anything though please add it!


Sure, no problem.

**Comment by Erlite** [comment] 2021-12-24 15:07
Worked for me after closing Origin and launching the Northstar launcher as admin.

**Comment by Riccorbypro** [comment] 2021-12-24 15:25
Just adding to the potential fixes here. I got the file corruption error, and fixed it using the same fix I've used for a while now:
1. Open Origin manually
2. Change your language under both Steam and Origin to something you don't normally play in (I use German personally)
3. Steam will want to download a 700MB-ish update, wait for that to finish
4. Launch the game

If this works for you then you can get back to your normal language by just switching it back and waiting for the update to download again. No idea why/how this works but it does and at least for me that's enough.

**Comment by KannaHayabusa** [comment] 2021-12-24 18:10
> 

Even if this were to solve the issue, one should not have to rely on giving admin access to a program that has no right to use it.

**Comment by KannaHayabusa** [comment] 2021-12-24 18:11
> I solve the problem by simply running it as admin. Just right click on the .exe or create a shortcut and right click on that, then properties>advanced>tick _run as adminstrator_>click ok>then apply and then run the game
> 
> ![image](https://user-images.githubusercontent.com/88533953/147340019-db65dde6-08df-4b8f-930e-816c48115dd6.png)

Even if this were to solve the issue, one should not have to rely on giving admin access to a program that has no right to use it.

**Comment by bonkmaykrQ** [comment] 2021-12-24 18:25
> Every time I got this error it was fixed by either restarting Origin, restarting my PC, or launching Northstar with Origin (not yet) started. This is an Origin error.
> 
> (I own both the Steam and Origin version of Titanfall 2 and when launching Northstar I use the Steam one)

Can confirm. I had this same issue a year ago on a vanilla client when playing in WINE. Restarting Origin fixed the problem.

Origin really doesn't seem to like us

**Comment by Aetrym** [comment] 2021-12-24 21:06
One user in the discord reported success by launching NorthStar, and then quickly quitting out of origin?

**Comment by Jaco909** [comment] 2021-12-24 21:13
Just had this same issue and was able to resolve it. Most likely was caused by Origin rapidly logging in and out. Having Origin repair the install fixed it.

**Comment by BaeTheDreamBoat** [comment] 2021-12-24 21:27
I think i found a solution:
1) open origin
2) log out and close
3) launch north star until it pops up with and origin install
4)sign in and play :)
let me know if this works for anyone else

**Comment by just12** [comment] 2021-12-25 18:12
Seems like updating to the latest [Visual C++ Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) release fixed it for me. I dont know if just installing the latest version works or it was that i uninstalled every other version. If someone is trying this be sure to install both x86 and x64 versions.

**Comment by zGLados** [comment] 2021-12-25 18:15
> I think i found a solution
> 
>     * if you just finished installing TF2 make sure to run it before running NorthStar
> 
>     * try running NorthStar as admin, if that doesn't work:
>       1) open origin
>       2) log out
>       3) close and make sure Origin is not running with task manager
>       4) launch NorthStar normally (not as admin) until it pops up with and origin login
>       5) sign in and play :)
>       let me know if this works for anyone else

This one fixed it for me, thanks

**Comment by Eruasa** [comment] 2021-12-25 18:24
> I think i found a solution
> 
> * if you just finished installing TF2 make sure to run it before running NorthStar
> * try running NorthStar as admin, if that doesn't work:
>   1) open origin
>   2) log out
>   3) close and make sure Origin is not running with task manager
>   4) launch NorthStar normally (not as admin) until it pops up with and origin login
>   5) sign in and play :)
>   let me know if this works for anyone else

Didn't work for me sadly. Tried your steps and before I tried to repair the game. Both didn't help.

**Comment by CosmicDreamsOfCode** [comment] 2021-12-25 18:48
Didn't work for me either.

**Comment by notthefoxx** [comment] 2021-12-26 11:50
> This was the fix that I found after a bit of troubleshooting
> 
>     * Verify integrity of game files
> 
>     * Launch the game normally through Steam
> 
>     * Close the game
> 
>     * Launch NorthstarLauncher.exe
> 
> 
> And it should be working fine



> I think i found a solution
> 
>     * if you just finished installing TF2 make sure to run it before running NorthStar
> 
>     * try running NorthStar as admin, if that doesn't work:
>       1) open origin
>       2) log out
>       3) close and make sure Origin is not running with task manager
>       4) launch NorthStar normally (not as admin) until it pops up with and origin login
>       5) sign in and play :)
>       let me know if this works for anyone else



> Seems like updating to the latest [Visual C++ Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) release fixed it for me. I dont know if just installing the latest version works or it was that i uninstalled every other version. If someone is trying this be sure to install both x86 and x64 versions.

I tried all of them, non of them works.

**Comment by BobTheBob9** [comment] 2021-12-26 21:45
after talking with some people, it seems the issue here is that origin will often complain if the game isn't started from the path origin has set for it (i.e. origin expects Titanfall 2 to start from Titanfall2.exe, not Titanfall2-unpacked.exe), unsure of a good solution here atm while still using the unpacked executable, since i'd rather not replace any files in the original install

**Comment by gwindle** [comment] 2021-12-28 21:46
I found a fix (atleast for me)
I added Titanfall2-unpacked.exe and NorthstarLauncher.exe as non-Origin games to librari and it seems to work every time.

**Comment by cusps** [comment] 2021-12-29 04:46
Unfortunately, none of the above fixes work for me. My current setup:

Origin Desktop App: Version 10.5.108.49699 - 770595
Northstar: Northstar.release.v1.2.1
Windows 10

**Comment by GeckoEidechse** [comment] 2021-12-29 11:28
@cusps I don't think Steam version has a guarantee to work either. That being said, I'd suggest going through the steps [described here](https://gecko-eidechse-gitbook.gitbook.io/r2northstar/installing-northstar/troubleshooting#engine-error) and see if any of those work for you.

If not the Steam version is currently only ~5$ and you can always refund it if it doesn't work either. Just note that owning both Steam and Origin version does seem to confuse Origin a bit, in particular it really likes to start the Steam version of Titanfall even if you tell it to launch the Origin one.
(Speaking from personal experience)

**Comment by skittles9823** [comment] 2021-12-29 11:30
Just an FYI, you do not need to have steam running to launch the steam version. Just have origin or EA Desktop running and be logged in before launching the steam version and you'll be good.

**Comment by cusps** [comment] 2021-12-29 16:24
I tried every solution, but as a last effort I tried using EA Desktop app. That worked well for me, sometimes it still gives the corruption error but is inconsistent. Works well enough for me.

**Comment by GeckoEidechse** [comment] 2022-01-03 11:16
(Edited title as this seems to affect all platforms according to comments made here)

**Comment by X30N1** [comment] 2022-01-03 12:54
Aight boys, I got a fix that worked for me:

CONTEXT (i think it's rather important)
I have 2 versions of titanfall 2. One was the original one on origin and the other one is the premium edition I got on a sale on steam. I'm using the premium version through steam.

THE FIX
So basically the re-installs on steam didn't do anything, so I decided to fool around on origin for a bit. somehow, I managed to force a window on origin asking me if I want to "update" the game (aka verify the game files), or proceed without updating. First time I did it it still crashed due to the error, but when I turned off automatic updates the game started working.

So I guess the problem is that each time you launch the game Origin might be checking for any changes in the files if you have automatic updates on?

**Comment by CYTMWIA** [comment] 2022-01-04 07:50
Found a solution from (R2NorthstarCN)[https://github.com/R2NorthstarCN].
1. Go to your `Titanfall2` folder.
2. Rename `Titanfall2.exe` to something else.
3. Rename `NorthstarLauncher.exe` to `Titanfall2.exe`.
4. Start game from Steam/Origin.

**Comment by p0358** [comment] 2022-01-06 11:06
Currently the official solution is to update Northstar and if you then get Origin error, then do these steps:
— add `-northstar` to your command line arguments/launch options field in Origin/Steam game options
— run the game with Origin/Steam instead of starting NorthstarLauncher.exe (important)
— error should be no more

The underlying issue is the same, but the error will not result in "file corruption" message anymore

**Comment by GeckoEidechse** [comment] 2022-01-08 14:28
Closing the issue now due to being fixed in the `v1.4.0`. For anyone coming across this thread make sure to update to [`v1.4.0`](https://github.com/R2Northstar/Northstar/releases) or higher first.

Keeping pinned for now though.

**Closed by GeckoEidechse** 2022-01-08 14:28 UTC
Labels: bug
