### ISSUE TITLE
DXGI_ERROR_DEVICE_HUNG Engine Error

### ISSUE THREAD

**Issue by getchoo** [R2Northstar/Northstar#282] opened 2022-05-21 21:19 UTC
### Bug
titanfall 2 crashed while playing gun game, giving me a `DXGI_ERROR_DEVICE_HUNG` engine error when it exited. i've never encountered this in the vanilla game, so i think it could be northstar. there was also no report of it in the logs, so i'm guessing it was a pretty hard crash...

the only thing i can think of that could cause this is that my gpu is overclocked, and there was a driver latency issue - but i've never encountered that in any other game so i'm not sure.

### Steps to reproduce

  1. start northstar through steam with the `-northstar` launch option
  2. join a server running gun game
  3. just play

### Specifications
  - Northstar version: v1.7.1
  - Platform: Steam

![error](https://user-images.githubusercontent.com/48872998/169669132-c704580b-6241-438b-96c6-8281d8ae621a.png)

**Comment by serebit** [comment] 2022-05-27 16:07
I've encountered this in vanilla. Titanfall 2 *really* doesn't like slightly unstable overclocks—from talking to one of the developers a while back, in the final release that's almost exclusively the cause of seeing this error. Drop your GPU clocks by 10-40 MHz and see if it goes away—if not, might be worth investigating

**Comment by Zanieon** [comment] 2024-11-29 23:51
This kind of issue is related to drivers and updates to them, and as mentioned, the game being completely vanilla still might give this issue, so not entirely Northstar related, closing.

**Closed by Zanieon** 2024-11-29 23:51 UTC
