### ISSUE TITLE
Unable to Launch NorthstarMP from Main Menu + Authentication error.

### ISSUE THREAD

**Issue by ColonelJRico** [R2Northstar/Northstar#95] opened 2021-12-31 14:29 UTC
![image](https://user-images.githubusercontent.com/96916702/147828156-f3e257b2-5682-44eb-9ffc-5d009baeb715.png)

I'm unable to launch Northstar MP, able to access lobby only after launching Campaign and wait around 2 minutes however no servers are available and any UI interaction boots me back to Main screen.

Authentication Failed dialogue apppears after a few minutes when doing nothing on Main screen.

**Comment by ColonelJRico** [comment] 2021-12-31 14:31
can send consol stuff if that helps

**Comment by MiloAkerman** [comment] 2021-12-31 20:25
Duplicate of #78

**Closed** 2022-01-01 00:36 UTC
