### ISSUE TITLE
Failed to initialize Origin, LSX Authentication Challenge failed

### ISSUE THREAD

**Issue by UPSimon78** [R2Northstar/Northstar#126] opened 2022-01-06 13:51 UTC
![image](https://user-images.githubusercontent.com/97235072/148391447-300e1b47-6148-43f7-8854-b0882e150d12.png)
When I start Northstar it opens the game, but my screen freezes ( except for my mouse) shortly after and  i get this error message. I then have to Alt+F4. I have the latest version, v1.4.0 right now, installed. Beside of that I also had the corupted file error. Has anyone experienced the same problem or can someone help?  I already tried the solutions from the troubleshooting. Thanks in advance.

**Comment by GeckoEidechse** [comment] 2022-01-06 17:18
Did you have any luck with [this section from the FAQ yet](https://r2northstar.gitbook.io/r2northstar-wiki/faq#q-i-keep-getting-the-engine-error-failed-to-initialize-origin-origin-core-seems-to-be-running-but-th)?

**Comment by TheFartMaster69** [comment] 2022-01-06 21:25
I have the exact same issue.

**Comment by UPSimon78** [comment] 2022-01-06 21:29
![image](https://user-images.githubusercontent.com/97235072/148454271-8006f5cc-2a9d-48e5-b905-c219a67aa3c2.png)
Yes, thank you very much. Adding the -northstar to your command line arguments/launch options field in Origin/Steam game options, as propossed by the faq, worked. But now when I try to join any server I get another error. I already tried different servers from different regions. Any ideas?

**Comment by Hitmanforrent** [comment] 2022-01-06 21:30
I was able to fix this issue by adding the -northstar to ns_startup_args, and forcing NorthstarLauncher.exe to run as admin.

**Comment by TheFartMaster69** [comment] 2022-01-06 21:31
Adding the -northstar also fixed it for me. Thanks!

**Comment by Hitmanforrent** [comment] 2022-01-06 21:36
Yeah for some reason I needed to force running as administrator in compatibility settings, as well as put the argument in ns_startup_args. The steam launch option didn't work for me personally.

**Comment by TheFartMaster69** [comment] 2022-01-06 21:37
> ![image](https://user-images.githubusercontent.com/97235072/148454271-8006f5cc-2a9d-48e5-b905-c219a67aa3c2.png) But now when I try to join any server I get another error. I already tried different servers from different regions. Any ideas?

Same here.

**Comment by UPSimon78** [comment] 2022-01-07 10:33
I started the game normally today and it looks like everything works fine, hope it will somehow work for you too.

**Comment by GeckoEidechse** [comment] 2022-01-07 10:45
@UPSimon78 @TheFartMaster69 "Authentication Failure" was caused by issues with the master server and should be fixed by now. Regarding "LSX Authentication Challenge failed", I'm gonna add it to the [troubleshooting section in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting) and then close this issue later.

**Comment by GeckoEidechse** [comment] 2022-01-08 14:23
Section is [added to the wiki now](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#failed-to-initialize-origin-origin-core-seems-to-be-running-but-the-lsx-authentication-challenge-fai).

Issue will stay pinned for the time being ^^

**Closed by GeckoEidechse** 2022-01-08 14:23 UTC
Labels: documentation

**Comment by cfacundo** [comment] 2022-02-03 15:11
As the [wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#failed-to-initialize-origin-origin-core-seems-to-be-running-but-the-lsx-authentication-challenge-fai) states (and @GeckoEidechse mentioned [before](https://github.com/R2Northstar/Northstar/issues/126#issuecomment-1008004374)) running the game first with **Steam** solved my problem, seems that part of the install was pending until then. Thanks!

**Comment by crackedeggyt** [comment] 2022-02-15 20:21
make sure that cloud save is off in origin, it really fs things up

**Comment by cwainwright** [comment] 2022-03-06 14:58
Adding -northstar to the Launch Options in steam fixed it for me, thanks!

**Comment by SlanFromBerserk** [comment] 2022-11-01 17:00
Make sure you're signed in. This might be super obvious, but for me the game wanted to run through Origin when I downloaded it through Steam. I fought with the program, even installed it twice more until I tried just running it normally. I had the exact same issue for hours. It signed me into an Origin account I forgot I even had and ran Northstar as it was supposed to.
