### ISSUE TITLE
Crush with TF2 from EA app

### ISSUE THREAD

**Issue by danstep1375** [R2Northstar/Northstar#514] opened 2023-07-13 18:07 UTC
### Bug
Replace this line with the bug you've encountered and what is the expected behaviour.

### Steps to reproduce

  1.
  2.
  3.

### Specifications
  - Northstar version:
  - Platform:

**Comment by stygia-dev** [comment] 2023-07-13 18:35
what

**Comment by JMM889901** [comment] 2023-07-13 18:35
what

**Comment by GeckoEidechse** [comment] 2023-07-13 19:28
Hi @danstep1375, we need a bit more information in order to figure out what may have caused the crash. Any logs etc would be needed figure this out.

I'm gonna close this issue for now as we cannot figure out the cause of the crash with the provided information. Feel free to add more info and I will re-open the issue accordingly. ^^

**Closed by GeckoEidechse** 2023-07-13 19:28 UTC
