### ISSUE TITLE
Error a1020002

### ISSUE THREAD

**Issue by 1llaN** [R2Northstar/Northstar#105] opened 2022-01-03 05:12 UTC
When i start Northstar i get This
Engine Error
Failed to initialize Origin: Origin seems to be running,but the LSX Authentication Challenge failed. No communication with Core is possible. [a1020002]
![Titanfall2-unpacked_sLuwuwJGeJ](https://user-images.githubusercontent.com/97011337/147901083-492f0b85-4d27-468b-94e4-59279f189fef.png)

**Comment by 1llaN** [comment] 2022-01-03 05:14
Restarting Origin was helped me

**Comment by The-Adam-The** [comment] 2022-01-19 18:39
> Did you find a resolution for this?

**Comment by 1llaN** [comment] 2022-01-20 14:55
Restarting Origin was helped me, but today this method not working. I have this error every time when I launch a game

**Comment by 1llaN** [comment] 2022-01-20 14:57
![image](https://user-images.githubusercontent.com/97011337/150363285-78a3243c-306a-4074-9e50-a09fd3816916.png)
It's same

**Comment by 1llaN** [comment] 2022-01-20 14:58
Last CMD lines
![image](https://user-images.githubusercontent.com/97011337/150363487-12c11ea9-2172-4f50-ab4f-e4a4697fd68b.png)

**Comment by GeckoEidechse** [comment] 2022-01-20 15:22
Make sure you have `v1.4.0` of Northstar and add `-northstar` to the startup arguments of Titanfall 2 in Steam/Origin (depending on where you bought the game). Then launch Titanfall 2 via Steam/Origin and Northstar should pop up.

See also [this entry in the wiki](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#failed-to-initialize-origin-origin-core-seems-to-be-running-but-the-lsx-authentication-challenge-fai) and this Github issue #126

**Comment by GeckoEidechse** [comment] 2022-01-20 15:23
Closing as a duplicate of #126 (the newer one has/had more activity)

**Closed by GeckoEidechse** 2022-01-20 15:23 UTC
