### ISSUE TITLE
Missing G2 scopes & occasional crashing when joining servers on 1.10.8-rc1

### ISSUE THREAD

**Issue by james-amarth** [R2Northstar/Northstar#382] opened 2022-12-01 20:03 UTC
### Bug
1.10.8-rc1 has missing G2 scope crosshairs and Threat Detector sight is a complete missing texture
Occasional crashing when joining servers
Both issues are related to the Gabirel Northstar OS mod, removing the mod fixes the issues https://discord.com/channels/920776187884732556/936310823612215326/1013226307657670736 

### Steps to reproduce
  1. Install the mod alongside other mods/by itself
  2. Try to join servers / use the G2 with any scope

### Specifications
  - Northstar version: 1.10.8-rc1
  - Platform: Steam | Linux

Screenshots:
![scope](https://user-images.githubusercontent.com/116909003/205148229-9232cabe-156e-40b2-9e46-074d918c9ff4.png)

**Comment by GeckoEidechse** [comment] 2022-12-01 22:21
Even using the mods folder shared by @james-amarth I cannot reproduce the G2 scope issue. As such I'm closing this as not reproducible for now. If anyone else can reproduce it please leave a comment here so I can re-open the issue ^^

**Closed by GeckoEidechse** 2022-12-01 22:21 UTC
