### ISSUE TITLE
Viewing map stats for Boomtown hard-locks the client

### ISSUE THREAD

**Issue by Jaco909** [R2Northstar/Northstar#14] opened 2021-12-24 17:55 UTC
Attempting to open the map stats for Boomtown (second map in the stats list), will freeze all input in the client and require a forced shutdown through task manager.

**Comment by MiloAkerman** [comment] 2022-02-04 23:04
Reproduced succesfully. Wtf.

**Comment by GeckoEidechse** [comment] 2022-04-13 21:53
Still an issue in `v1.6.3`, damn o_O

**Comment by MiloAkerman** [comment] 2022-04-13 22:19
Listen Gecko my esteemed fellow I haven't touched this game in a month because I fear even so much as opening this bug again will give me irreversible brain damage

**Comment by GeckoEidechse** [comment] 2022-04-14 08:55
@MiloAkerman Emma actually found the issue and has a fix :D
Spoiler alert: The reason it happened in the first place is really stupid and is caused by Respawn's own code.

https://github.com/R2Northstar/NorthstarMods/pull/307

**Comment by emma-miler** [comment] 2022-04-29 21:51
Fixed in 1.6.4

**Comment by GeckoEidechse** [comment] 2022-04-29 21:52
https://github.com/R2Northstar/NorthstarMods/pull/307

**Closed** 2022-04-29 21:52 UTC
Labels: bug, reproducible
