### ISSUE TITLE
Dedicated server using exorbitant amounts of vRAM and RAM

### ISSUE THREAD

**Issue by Bobbyperson12** [R2Northstar/Northstar#149] opened 2022-01-13 03:42 UTC
### Bug
If left unchecked, after several hours my dedicated server will begin to use more and more vRAM and RAM. The most I've seen so far is 8 gigs of RAM and 12 gigs of vRAM (amount on my card). Eventually it crashed my entire computer.

####  Some screenshots:
https://owo.whats-th.is/6xxF266.png (column on the right is vRAM)
https://owo.whats-th.is/5pWC3j8.png
https://owo.whats-th.is/6gswiXb.png
https://owo.whats-th.is/4iyTLcd.png

### Steps to reproduce
I haven't done anything unique when it comes to dedicated servers, I'll post my configs though.
From what I can tell, no log was made when my computer crashed, the time stamps don't connect.
https://pastebin.com/L8KNdnW6 ns_startup_args_dedi.txt
https://pastebin.com/yKHLACMV ns_startup_args.txt
https://pastebin.com/wwYapvCc autoexec_ns_server.cfg

### Specifications
  - Northstar version: v1.4.0
  - Platform: Steam
  - Processor: i7-10700F
  - RAM: 16 GB
  - GPU: Nvidia 3060

**Comment by Vexbane** [comment] 2022-01-19 13:38
In doing test with no mods and simple start up arguments - I can confirm this ram usage increase with the change of each map.  As a test, I set map on 1 minute cycles.  Approximately every 15 minutes the server increased in ram usage by 2gb until it finally crashed our clan's ark server and titanfall / northstar.  Northstar reached about 11.5 gb b4 the crash.  

restarted a new test, using quick cpu to 'clean memory' and confirmed the 2gb increase - every 15 minutes (with map rotation every 60 seconds)

- https://discord.com/channels/920776187884732556/924468488028971059/933271617730146324
- https://discord.com/channels/920776187884732556/924468488028971059/933291641043816498
- https://discord.com/channels/920776187884732556/924468488028971059/933293860208144385
- https://discord.com/channels/920776187884732556/924468488028971059/933296914420621342
- https://discord.com/channels/920776187884732556/924468488028971059/933309379455885332

**Comment by pg9182** [comment] 2022-01-19 15:33
I'm interested in how people's Linux servers are performing. My docker image contains stubs for d3d11, so the vRAM usage won't be a problem there, but the RAM usage for Northstar itself on startup seems to be lower too.

**Comment by Bobbyperson12** [comment] 2022-01-21 18:22
I have a working theory that once the vRAM fills up the RAM starts filling too, I'm going to have to monitor it more closely to confirm or deny this.

**Comment by barnabwhy** [comment] 2022-01-23 12:08
It may also be due to script calls.
With cl_showfps on, the script value slowly increases over time (it rises and falls but longer term you see a net increase) plus it has a k on the end so i reckon that measures kB.
Perhaps this could mean there’s just some script calls that don’t get removed from memory(?)

**Comment by pg9182** [comment] 2022-02-16 11:35
I've got my stubs running on Windows:

https://discord.com/channels/920776187884732556/943369531538173993/943369533194928240

After cycling through a few maps, with my stubs:

![image](https://user-images.githubusercontent.com/96569817/154256462-d18a41e6-60b2-4f68-94b9-cf02d93f2c56.png)

With softwared3d11:

![image](https://user-images.githubusercontent.com/96569817/154256566-be904301-8429-4f93-b9ec-8e1127f8e88a.png)

With a real gpu:

![image](https://user-images.githubusercontent.com/96569817/154256640-b96077bf-6eb2-4ac8-8fd6-e9f4f0d84648.png)

**Comment by emma-miler** [comment] 2022-02-19 13:28
Fixed as of r2northstar/northstarlauncher#81

**Closed** 2022-04-07 14:10 UTC
Labels: bug
