### ISSUE TITLE
Vanilla via NorthstarLauncher broken on `v1.13.1+`

### ISSUE THREAD

**Issue by CooldudePUGS** [R2Northstar/Northstar#473] opened 2023-04-29 00:11 UTC
### Bug
Vanilla doesn't connect via NorthstarLauncher when disabling core mods and using the launch option `-norestrictservercommands`

### Steps to reproduce
  1. Use vanilla via Northstar (disable all 3 core mods, use `-norestrictservercommands` launch arg)
  2. Open Vanilla multiplayer
  3. Attempt to connect to a Vanilla match, and fail

### Specifications
  - Northstar version:1.13.1
  - Platform: Steam

### Screenshots
Attempting to connect to Private match on Vanilla using Northstar 1.13.1
![Attempting to connect to Private match on Vanilla using Northstar 1.13.1](https://user-images.githubusercontent.com/70904206/235272000-f7bec1dc-bfc9-4152-9ff5-6e0073e77e5f.png)

Disconnecting from a Vanilla match after waiting in queue on Northstar 1.13.1 (tried multiple times, all failed while normal vanilla worked without issue)
![Disconnecting from a Vanilla match after waiting in queue on Northstar 1.13.1 (tried multiple times, all failed while normal vanilla worked without issue)](https://user-images.githubusercontent.com/70904206/235272022-cde859af-e248-45db-81a7-29d5ca422ba0.png)

Normal Vanilla was functioning fine at the time
![Normal Vanilla was functioning fine at the time](https://user-images.githubusercontent.com/70904206/235272061-32743a3c-b1ce-452b-a3f7-386823ee3610.png)

**Comment by GeckoEidechse** [comment] 2023-04-29 11:38
Anyone who'd like to look into this try older versions, in particular `v1.12.7` or earlier (`v1.13.0` is already known to be broken for other reasons).

Once we find the last working version (i.e. going one version higher breaks it) we can then use that information to find the cause of the breakage.

**Comment by GeckoEidechse** [comment] 2023-06-11 20:18
`v1.14.2` seems to work fine but it keeps spamming

```
[22:14:39] [SCRIPT CL] [error] Call was unable to find function with name 'NorthstarCodeCallback_GenerateGameState'. Is it global?
[22:14:39] [SCRIPT UI] [error] Call was unable to find function with name 'NorthstarCodeCallback_GenerateUIPresence'. Is it global?
```
in logs. Gonna make a separate issue for that and close this one as resolved ^^

**Closed by GeckoEidechse** 2023-06-11 20:18 UTC
Labels: bug, help wanted, info needed

**Comment by EnderBoy9217** [comment] 2023-08-17 15:57
@GeckoEidechse This issue is pinned too
