### ISSUE TITLE
"File Corruption detected. Please repair or re-install the game"

### ISSUE THREAD

**Issue by WarteAufBlitz** [R2Northstar/Northstar#93] opened 2021-12-31 11:21 UTC
I'm trying to install northstar for steam but keep getting this message. It loads, gets just past the Respawn logo then crashes with this message. I've tried a full install but that hasn't worked. The last line in the console before the crash is "CreateInterface CLIENT VP4002" If that helps, and if necessaary, i can send the rest of the console.
Any help is appreciated.

**Comment by Casper1123** [comment] 2021-12-31 13:14
Have you tried the following steps? These works for me:
- Verify game files
- Close Steam/Origin completely
- launch vanilla TF
- launch Northstar

If this has not worked, you can see when it gets an engine error because the console will display only 2 lines for a short little while:
'
[14:13:32] [info] Enabling hook LoadLibraryExAHook
[14:13:32] [info] Enabling hook LoadLibraryExWHook
'
and then a couple seconds after it will start running other code
When functioning correctly it starts running everything else immediately.

**Comment by Gamer92000** [comment] 2021-12-31 14:30
This exact error happens to me only when the game is launched prior to EA / Origin running. Once Origin is open I can start the Northstar client again and it works just fine.

**Comment by Aragami-delp** [comment] 2021-12-31 14:43
I did all of the above. Didn't work, but after a PC restart it worked (for some reason).

**Comment by Gamer92000** [comment] 2021-12-31 14:48
This is a duplicate of #6 btw.

**Comment by WarteAufBlitz** [comment] 2021-12-31 16:41
> Have you tried the following steps? These works for me:
> 
>     * Verify game files
> 
>     * Close Steam/Origin completely
> 
>     * launch vanilla TF
> 
>     * launch Northstar
> 
> 
> If this has not worked, you can see when it gets an engine error because the console will display only 2 lines for a short little while: ' [14:13:32] [info] Enabling hook LoadLibraryExAHook [14:13:32] [info] Enabling hook LoadLibraryExWHook ' and then a couple seconds after it will start running other code When functioning correctly it starts running everything else immediately.

This worked, thanks. Cheers for the help and I'll hope to see you in game

**Closed** 2021-12-31 16:41 UTC
