### ISSUE TITLE
Cannot change Pilot load out,  results in game crashes 

### ISSUE THREAD

**Issue by ggrcrash** [R2Northstar/Northstar#100] opened 2022-01-01 04:56 UTC
I got the first loadout...cannot change it...reinstalled regur titanfall2....no problem except ddossed to hell. New complete install of Northstar client, only one loadout , except for gun game, but I am at the mercy of the server to change loadouts based on how I died or was killed.

**Comment by ggrcrash** [comment] 2022-01-01 23:21
It says, There was a problem processing game logic
Please try again
_items.nut#4753
[UI] The index "Invalid_Ref"
Does not exist

**Comment by birdsnestt** [comment] 2022-01-04 17:11
Did you ever get a solution for this?

**Comment by ggrcrash** [comment] 2022-01-04 20:31
Nope....still an issue. I was going to wait for another client release,
then totally reinstall game from scratch and then start from the new client
and see what happens.

**Comment by abarichello** [comment] 2022-01-06 19:21
Can you test this again with the newest release?

**Comment by birdsnestt** [comment] 2022-01-06 19:38
It is still an issue - same error message

**Comment by ggrcrash** [comment] 2022-01-08 04:11
Actually yes...still an issue, even with a complete reinstall of
titanfall2, as well as the most current Northstar client. Still stuck with
one loadout. On a good note, I've definitely become more proficient with
it. EPGeesus...still hate the charge rifle for titans, but I guess I will
have to manage until it's fixed...

**Comment by MacManus26** [comment] 2022-02-05 13:44
Updating thread to state i'm having the same issue. 
Did a complete reinstall of both TF2 and NS. No mods installed. 
This crash started when i tried to install skins through Pandora's skin tool, so maybe that has something to do with it ?

**Comment by yougotpauled** [comment] 2022-02-12 18:15
Made a github account just to say I have the same issue it started with 1.4.1.
I reinstalled everything even TF2 and I couldn't open pilot loadout.
same mods as before the update and now I can only play with my cloak loadout.

**Comment by GeckoEidechse** [comment] 2022-02-12 19:10
> Made a github account just to say I have the same issue it started with 1.4.1.

Have you tried 1.4.2 yet? Although there shouldn't be any changes in either 1.4.1 nor 1.4.2 compared to 1.4.0 that has an effect on pilot loadouts, I just wanna make sure whether it's still an issue in the newest version.

**Comment by yougotpauled** [comment] 2022-02-12 19:17
> > Made a github account just to say I have the same issue it started with 1.4.1.
> 
> Have you tried 1.4.2 yet? Although there shouldn't be any changes in either 1.4.1 nor 1.4.2 compared to 1.4.0 that has an effect on pilot loadouts, I just wanna make sure whether it's still an issue in the newest version.

yes, nothing has worked to fix it.
I haven't asked around for fixes only looked if this was already a thing and it is and it doesn't look very fixable,
not from my end at least so I'm just gonna wait for an update.

**Comment by GeckoEidechse** [comment] 2022-02-12 19:33
Hmm, crashes on pilot loadout menu are usually caused by messed up pdata (it stores your pilot loadouts etc).

`v1.5.0` adds a console command to reset your pdata called `ns_resetpersistence`. Unless you're keen on messing around with [pre-releases](https://github.com/R2Northstar/Northstar/actions/runs/1810227112) I'd suggest just waiting for `v1.5.0` release and then applying that console command. ^^

If you after entering that command on the new release still crash on pilot loadout menu we might have a bigger issue at hand :/

**Comment by yougotpauled** [comment] 2022-02-14 05:00
its late at night but I think I figured it out. I put the paid skins on some of my weapons via a mod but never reinstalled it. Ill try reinstalling tomorrow I hope that works.

**Comment by MacManus26** [comment] 2022-02-14 07:04
> 

Hey, i think i did that too now that you mention it... Let me know how that goes if you reinstall it

**Comment by GeckoEidechse** [comment] 2022-02-14 09:58
Reinstalling likely won't fix it then cause your loadout is saved on the master server and re-applied when you launch Northstar.

That being said, [`v1.5.0` is out now](https://github.com/R2Northstar/Northstar/releases), you can enter the command `ns_resetpersistence` in the in-game console on main menu ([check here how to open it](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/commands#opening-the-console)) and use that to reset your loadouts. After entering the command, join any non-full server in a public match and your loadouts etc should be reset.

Keep in mind, AFAIK this also resets progression (your in-game level etc). As all guns and skins are unlocked by default this shouldn't be much of a further issue but might be something to keep in mind, if you value your in-game progression.
Note that you can set XP levels to arbitrary values using various commands so you can always get it back to roughly your previous level before reset. Just screenshot the old value so you remember what it was if you care about that sorta stuff.

**Comment by yougotpauled** [comment] 2022-02-14 21:14
I don't think the mod that I used is still up, I've looked for it everywhere. if anyone remembers the exact name or has a link that'd be nice. I think that would fix it without having to remake all of my loadouts, and Id like the paid skins either way.

**Comment by MacManus26** [comment] 2022-02-15 09:36
> I don't think the mod that I used is still up, I've looked for it everywhere. if anyone remembers the exact name or has a link that'd be nice. I think that would fix it without having to remake all of my loadouts, and Id like the paid skins either way. ima wait an hour and then just reset everything cause I want to play 1.5.
> 
> (I have reset my loadout using the command and it worked)

IIRC (maybe devs will be able to confirm) the mod unlocking all paid skins was integrated as part of the basic Northstar package a few updates ago. So you should have these skins by default.

Nice to hear that the command worked, I'll be trying that in the near future.

**Comment by ggrcrash** [comment] 2022-02-15 15:19
Problem repaired...thanks for the effort 😎

**Comment by GeckoEidechse** [comment] 2022-02-16 10:48
Before I close this issue, what was the fix for you?

**Comment by ggrcrash** [comment] 2022-02-16 11:38
1.5.0 version and the ns _ reset command...worked like a charm...

**Comment by GeckoEidechse** [comment] 2022-02-16 11:50
Perfect, good to know. Thanks <3

**Closed by GeckoEidechse** 2022-02-16 11:50 UTC
Labels: bug
