### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by xamionex** [R2Northstar/Northstar#141] opened 2022-01-11 11:10 UTC
## Issue for Server Crashes

**Comment by xamionex** [comment] 2022-01-11 11:11
![image](https://user-images.githubusercontent.com/57235791/148932266-b3817017-306d-43f6-bc61-fc2b23cc4194.png)
[12:08:35] [info] [DEDICATED PRINT] [8480.150]
[12:08:35] [info] [DEDICATED PRINT] FatalError:
[12:08:35] [info] [DEDICATED PRINT] Tried to remove entity #93:npc_titan [93]:models/titans/medium/titan_medium_ajax.mdl while a player (#6, 'BloxytheFox', lifestate #0) was attached.
Tried to remove entity #93:npc_titan [93]:models/titans/medium/titan_medium_ajax.mdl while a player (#6, 'BloxytheFox', lifestate #0) was attached.

**Comment by xamionex** [comment] 2022-01-11 14:03
I believe mp_gamemode was Skirmish
```
[15:01:06] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Given object is not an entity (type = null)
[15:01:06] [info] [SERVER SCRIPT]  -> armBadge.ClearParent()
[15:01:06] [info] [SERVER SCRIPT]
CALLSTACK
*FUNCTION [UpdateTitanArmBadge()] titan/sh_titan.gnut line [286]
*FUNCTION [CPlayer()] class/CPlayer.nut line [327]
*FUNCTION [CPlayer()] class/CPlayer.nut line [306]
*FUNCTION [PilotBecomesTitan()] mp/_titan_transfer.nut line [582]
*FUNCTION [RespawnAsTitan()] mp/_base_gametype_mp.gnut line [462]

[15:01:06] [info] [SERVER SPEW_WARNING] point_viewcontrol point_viewcontrol [329] called Disable when it wasn't the players active view entity.
[15:01:06] [error] Northstar has crashed! a minidump has been written and exception info is available below:
[15:01:06] [error] Cause: Access Violation
Attempted to read from: 0x00000000
[15:01:06] [error] At: engine.dll + 0x247d3a
[15:01:06] [error]     Northstar.dll + 0x7ffd41fb9e60
[15:01:06] [error]     ntdll.dll + 0x7ffda133bfea
[15:01:06] [error]     ntdll.dll + 0x7ffda12f5812
[15:01:06] [error]     ntdll.dll + 0x7ffda136730e
[15:01:06] [error]     engine.dll + 0x7ffc94357d3a
[15:01:06] [error]     engine.dll + 0x7ffc94527466
[15:01:06] [error]     engine.dll + 0x7ffc94230c2f
[15:01:06] [error]     engine.dll + 0x7ffc94230542
[15:01:06] [error]     engine.dll + 0x7ffc9427db55
[15:01:06] [error]     engine.dll + 0x7ffc942d88c0
[15:01:06] [error]     Northstar.dll + 0x7ffd41fa18bc
[15:01:06] [error]     engine.dll + 0x7ffc942d652f
[15:01:06] [error]     engine.dll + 0x7ffc944a0e2d
[15:01:06] [error]     engine.dll + 0x7ffc942d79d9
[15:01:06] [error]     engine.dll + 0x7ffc942d793c
[15:01:06] [error]     launcher.dll + 0x7ffd774f5afd
[15:01:06] [error]     launcher.dll + 0x7ffd774f5afd
[15:01:06] [error]     launcher.dll + 0x7ffd774ed386
[15:01:06] [error]     NorthstarLauncher.exe + 0x7ff7e8273bbd
[15:01:06] [error]     NorthstarLauncher.exe + 0x7ff7e8276d40
[15:01:06] [error]     KERNEL32.DLL + 0x7ffda0b754e0
[15:01:06] [error]     ntdll.dll + 0x7ffda12c485b
[15:01:06] [error] RAX: 0x0
[15:01:06] [error] RBX: 0x7ffc948f56d0
[15:01:06] [error] RCX: 0x0
[15:01:06] [error] RDX: 0x0
[15:01:06] [error] RSI: 0x7ffca71ebb78
[15:01:06] [error] RDI: 0x7ffca71ebb78
[15:01:06] [error] RBP: 0x7ffca71ebd88
[15:01:06] [error] RSP: 0x57c39af560
[15:01:06] [error] R8: 0x7ffca71ebb78
[15:01:06] [error] R9: 0x65
[15:01:06] [error] R10: 0x7ffca71ebd94
[15:01:06] [error] R11: 0x7ffc947178ec
[15:01:06] [error] R12: 0x0
[15:01:06] [error] R13: 0x0
[15:01:06] [error] R14: 0xffffffff
[15:01:06] [error] R15: 0x1
```

**Comment by xamionex** [comment] 2022-01-11 21:01
## Skirmish
```[16:39:18] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Entity is null
[16:39:18] [info] [SERVER SCRIPT]  -> soul.soul.lastOwner = player
[16:39:18] [info] [SERVER SCRIPT]
CALLSTACK
*FUNCTION [PilotBecomesTitan()] mp/_titan_transfer.nut line [515]
*FUNCTION [RespawnAsTitan()] mp/_base_gametype_mp.gnut line [462]

[16:39:18] [info] [SERVER SCRIPT] LOCALS
[soul] NULL
[fullCopy] true
[titan] ENTITY (npc_titan [265] (NPC "npc_titan_auto_stryder_sniper" at <-152.918 -547.427 1747.53>))
[player] ENTITY (player YODIROVANIJ [3] (player "YODIROVANIJ" at <-152.918 -547.427 1747.53>))
[this] TABLE
[xyOffset] <43.9989, 0.312859, 520>
[camera] ENTITY (point_viewcontrol [350] at <-117.91 -574.082 2267.53>)
[titan] ENTITY (npc_titan [265] (NPC "npc_titan_auto_stryder_sniper" at <-152.918 -547.427 1747.53>))
[warpAttach] unknown struct
[model] $"models/titans/light/titan_light_raptor.mdl"
[titanLoadout] unknown struct
[spawnpoint] ENTITY (info_spawnpoint_titan info_spawnpoint_titan_10 [0] at <-152.92 -547.43 -127.969>)
[manualPosition] false
[player] ENTITY (player YODIROVANIJ [3] (player "YODIROVANIJ" at <-152.918 -547.427 1747.53>))
[this] TABLE

DIAGPRINTS

[16:39:18] [info] [SERVER SPEW_WARNING] point_viewcontrol point_viewcontrol [350] called Disable when it wasn't the players active view entity.
[16:39:18] [error] Northstar has crashed! a minidump has been written and exception info is available below:
[16:39:18] [error] Cause: Access Violation
Attempted to read from: 0x00000000
[16:39:18] [error] At: engine.dll + 0x247d3a
[16:39:18] [error]     Northstar.dll + 0x7ffd3b7c9e60
[16:39:18] [error]     ntdll.dll + 0x7ffda133bfea
[16:39:18] [error]     ntdll.dll + 0x7ffda12f5812
[16:39:18] [error]     ntdll.dll + 0x7ffda136730e
[16:39:18] [error]     engine.dll + 0x7ffc6a7d7d3a
[16:39:18] [error]     engine.dll + 0x7ffc6a9a7466
[16:39:18] [error]     engine.dll + 0x7ffc6a6b0c2f
[16:39:18] [error]     engine.dll + 0x7ffc6a6b0542
[16:39:18] [error]     engine.dll + 0x7ffc6a6fdb55
[16:39:18] [error]     engine.dll + 0x7ffc6a7588c0
[16:39:18] [error]     Northstar.dll + 0x7ffd3b7b18bc
[16:39:18] [error]     engine.dll + 0x7ffc6a75652f
[16:39:18] [error]     engine.dll + 0x7ffc6a920e2d
[16:39:18] [error]     engine.dll + 0x7ffc6a7579d9
[16:39:18] [error]     engine.dll + 0x7ffc6a75793c
[16:39:18] [error]     launcher.dll + 0x7ffd41b25afd
[16:39:18] [error]     launcher.dll + 0x7ffd41b25afd
[16:39:18] [error]     launcher.dll + 0x7ffd41b1d386
[16:39:18] [error]     NorthstarLauncher.exe + 0x7ff7b4443bbd
[16:39:18] [error]     NorthstarLauncher.exe + 0x7ff7b4446d40
[16:39:18] [error]     KERNEL32.DLL + 0x7ffda0b754e0
[16:39:18] [error]     ntdll.dll + 0x7ffda12c485b
[16:39:18] [error] RAX: 0x0
[16:39:18] [error] RBX: 0x7ffc6ad756d0
[16:39:18] [error] RCX: 0x0
[16:39:18] [error] RDX: 0x0
[16:39:18] [error] RSI: 0x7ffc7d66bb78
[16:39:18] [error] RDI: 0x7ffc7d66bb78
[16:39:18] [error] RBP: 0x7ffc7d66bd88
[16:39:18] [error] RSP: 0x29791af060
[16:39:18] [error] R8: 0x7ffc7d66bb78
[16:39:18] [error] R9: 0x65
[16:39:18] [error] R10: 0x7ffc7d66bd94
[16:39:18] [error] R11: 0x7ffc6ab978ec
[16:39:18] [error] R12: 0x0
[16:39:18] [error] R13: 0x0
[16:39:18] [error] R14: 0xffffffff
[16:39:18] [error] R15: 0x1```

**Comment by neverkarma** [comment] 2022-01-11 21:50
FFA COLONIE 30player

2022-01-11 22:29:14.504] [info] [SERVER SPEW_MESSAGE] Setting player "player SucharitBhakdi [7]" predicted first person proxy model to "models/weapons/arms/pov_titan_heavy_deadbolt.mdl" (class "titan_ogre_minigun")
[2022-01-11 22:29:14.505] [info] [SERVER SPEW_WARNING] point_viewcontrol point_viewcontrol [825] called Disable when it wasn't the players active view entity.
[2022-01-11 22:29:14.693] [info] [SERVER SPEW_MESSAGE] Setting player "player datpup1012 [14]" predicted first person proxy model to "" (class "spectator")
[2022-01-11 22:29:14.693] [info] [SERVER SCRIPT] respawn delay 0
[2022-01-11 22:29:15.811] [info] [SERVER SPEW_MESSAGE] Setting player "player smashedplate21 [11]" predicted first person proxy model to "" (class "spectator")
[2022-01-11 22:29:15.811] [info] [SERVER SCRIPT] respawn delay 0
[2022-01-11 22:29:17.580] [error] Northstar has crashed! a minidump has been written and exception info is available below:
[2022-01-11 22:29:17.580] [error] Cause: Access Violation
Attempted to read from: 0xffffffffffffffff
[2022-01-11 22:29:17.580] [error] At: tier0.dll + 0x20410
[2022-01-11 22:29:17.582] [error]     Northstar.dll + 0x7ffb997a9e60
[2022-01-11 22:29:17.582] [error]     ntdll.dll + 0x7ffbc7588a3c
[2022-01-11 22:29:17.582] [error]     ntdll.dll + 0x7ffbc7561276
[2022-01-11 22:29:17.582] [error]     ntdll.dll + 0x7ffbc75b0bfe
[2022-01-11 22:29:17.582] [error]     tier0.dll + 0x7ffb999e0410
[2022-01-11 22:29:17.582] [error]     tier0.dll + 0x7ffb999e1e1b
[2022-01-11 22:29:17.582] [error]     server.dll + 0x1becb46f0a0
[2022-01-11 22:29:17.582] [error]     server.dll + 0x1becba3dd63
[2022-01-11 22:29:17.582] [error]     server.dll + 0x1becb81f410
[2022-01-11 22:29:17.582] [error]     server.dll + 0x1becb52682d
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb26559582
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb26558ea5
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb265aa0e0
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb265a9707
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb265a7970
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb265be9f6
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb265bdbcb
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb266188c0
[2022-01-11 22:29:17.582] [error]     Northstar.dll + 0x7ffb997918bc
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb2661652f
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb267e0e2d
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb266179d9
[2022-01-11 22:29:17.582] [error]     engine.dll + 0x7ffb2661793c
[2022-01-11 22:29:17.582] [error]     launcher.dll + 0x7ffba7c35afd
[2022-01-11 22:29:17.582] [error]     launcher.dll + 0x7ffba7c35afd
[2022-01-11 22:29:17.582] [error]     launcher.dll + 0x7ffba7c2d386
[2022-01-11 22:29:17.582] [error]     NorthstarLauncher.exe + 0x7ff720e43bbd
[2022-01-11 22:29:17.583] [error]     NorthstarLauncher.exe + 0x7ff720e46d40
[2022-01-11 22:29:17.583] [error]     KERNEL32.DLL + 0x7ffbc6907034
[2022-01-11 22:29:17.583] [error]     ntdll.dll + 0x7ffbc7562651
[2022-01-11 22:29:17.583] [error] RAX: 0xc79fdf9a301a8ee1
[2022-01-11 22:29:17.583] [error] RBX: 0x1bf2ebd0000
[2022-01-11 22:29:17.583] [error] RCX: 0x3e9180dbad83808f
[2022-01-11 22:29:17.583] [error] RDX: 0x0
[2022-01-11 22:29:17.583] [error] RSI: 0x12100018088
[2022-01-11 22:29:17.583] [error] RDI: 0x1be8db90010
[2022-01-11 22:29:17.583] [error] RBP: 0x50000
[2022-01-11 22:29:17.583] [error] RSP: 0xb28ddaf060
[2022-01-11 22:29:17.583] [error] R8: 0xba0
[2022-01-11 22:29:17.583] [error] R9: 0x12100038004
[2022-01-11 22:29:17.583] [error] R10: 0x1bf2ebd0000
[2022-01-11 22:29:17.583] [error] R11: 0x0
[2022-01-11 22:29:17.583] [error] R12: 0x1bf2e3affc0
[2022-01-11 22:29:17.583] [error] R13: 0x128
[2022-01-11 22:29:17.583] [error] R14: 0x1bf2f37ffc0
[2022-01-11 22:29:17.583] [error] R15: 0x1bf2ec1ffc0

**Comment by xamionex** [comment] 2022-01-12 06:42
## mp_gamemode ps
![image](https://user-images.githubusercontent.com/57235791/149077189-9afc6445-7df1-40ed-9085-8f01b0b5d170.png)
[07:39:14] [info] [SERVER SPEW_MESSAGE] CHANGE LEVEL: mp_drydock
[07:39:14] [info] [SERVER SPEW_MESSAGE] CVScriptGameSystem::LevelShutdownPreEntity()
[07:39:14] [info] DestroyVM SERVER 0x1f3162eea00
[07:39:14] [info] [SERVER SPEW_MESSAGE] CVScriptGameSystem::LevelShutdownPreEntity()
[07:39:14] [info] MountVPK vpk/client_mp_drydock.bsp
[07:39:14] [info] MountVPK R2Northstar/mods\Northstar.Custom\vpk\client_mp_northstar_common.bsp
[07:39:14] [info] 0x1f310cc07c0
[07:39:21] [info] [DEDICATED PRINT] FatalError:
[07:39:21] [info] [DEDICATED PRINT] FatalError:
[07:39:21] [info] [DEDICATED PRINT] Couldn't create texture "world\walls\construction_metal_form_walls_dented_03_nml": error code 8007000e

Couldn't create texture "world\walls\construction_metal_form_walls_dented_03_nml": error code 8007000e

**Comment by MiloAkerman** [comment] 2022-02-01 21:43
> I believe mp_gamemode was Skirmish
> 
> ```
> [15:01:06] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Given object is not an entity (type = null)
> [15:01:06] [info] [SERVER SCRIPT]  -> armBadge.ClearParent()
> [15:01:06] [info] [SERVER SCRIPT]
> CALLSTACK
> *FUNCTION [UpdateTitanArmBadge()] titan/sh_titan.gnut line [286]
> *FUNCTION [CPlayer()] class/CPlayer.nut line [327]
> *FUNCTION [CPlayer()] class/CPlayer.nut line [306]
> *FUNCTION [PilotBecomesTitan()] mp/_titan_transfer.nut line [582]
> *FUNCTION [RespawnAsTitan()] mp/_base_gametype_mp.gnut line [462]
> 
> [15:01:06] [info] [SERVER SPEW_WARNING] point_viewcontrol point_viewcontrol [329] called Disable when it wasn't the players active view entity.
> [15:01:06] [error] Northstar has crashed! a minidump has been written and exception info is available below:
> [15:01:06] [error] Cause: Access Violation
> Attempted to read from: 0x00000000
> [15:01:06] [error] At: engine.dll + 0x247d3a
> [15:01:06] [error]     Northstar.dll + 0x7ffd41fb9e60
> [15:01:06] [error]     ntdll.dll + 0x7ffda133bfea
> [15:01:06] [error]     ntdll.dll + 0x7ffda12f5812
> [15:01:06] [error]     ntdll.dll + 0x7ffda136730e
> [15:01:06] [error]     engine.dll + 0x7ffc94357d3a
> [15:01:06] [error]     engine.dll + 0x7ffc94527466
> [15:01:06] [error]     engine.dll + 0x7ffc94230c2f
> [15:01:06] [error]     engine.dll + 0x7ffc94230542
> [15:01:06] [error]     engine.dll + 0x7ffc9427db55
> [15:01:06] [error]     engine.dll + 0x7ffc942d88c0
> [15:01:06] [error]     Northstar.dll + 0x7ffd41fa18bc
> [15:01:06] [error]     engine.dll + 0x7ffc942d652f
> [15:01:06] [error]     engine.dll + 0x7ffc944a0e2d
> [15:01:06] [error]     engine.dll + 0x7ffc942d79d9
> [15:01:06] [error]     engine.dll + 0x7ffc942d793c
> [15:01:06] [error]     launcher.dll + 0x7ffd774f5afd
> [15:01:06] [error]     launcher.dll + 0x7ffd774f5afd
> [15:01:06] [error]     launcher.dll + 0x7ffd774ed386
> [15:01:06] [error]     NorthstarLauncher.exe + 0x7ff7e8273bbd
> [15:01:06] [error]     NorthstarLauncher.exe + 0x7ff7e8276d40
> [15:01:06] [error]     KERNEL32.DLL + 0x7ffda0b754e0
> [15:01:06] [error]     ntdll.dll + 0x7ffda12c485b
> [15:01:06] [error] RAX: 0x0
> [15:01:06] [error] RBX: 0x7ffc948f56d0
> [15:01:06] [error] RCX: 0x0
> [15:01:06] [error] RDX: 0x0
> [15:01:06] [error] RSI: 0x7ffca71ebb78
> [15:01:06] [error] RDI: 0x7ffca71ebb78
> [15:01:06] [error] RBP: 0x7ffca71ebd88
> [15:01:06] [error] RSP: 0x57c39af560
> [15:01:06] [error] R8: 0x7ffca71ebb78
> [15:01:06] [error] R9: 0x65
> [15:01:06] [error] R10: 0x7ffca71ebd94
> [15:01:06] [error] R11: 0x7ffc947178ec
> [15:01:06] [error] R12: 0x0
> [15:01:06] [error] R13: 0x0
> [15:01:06] [error] R14: 0xffffffff
> [15:01:06] [error] R15: 0x1
> ```

this issue specifically should be fixed with R2Northstar/NorthstarMods#173

**Comment by MiloAkerman** [comment] 2022-02-01 23:37
> ## Skirmish
> ```
> [16:39:18] [info] [SERVER SCRIPT]  -> soul.soul.lastOwner = player
> [16:39:18] [info] [SERVER SCRIPT]
> CALLSTACK
> *FUNCTION [PilotBecomesTitan()] mp/_titan_transfer.nut line [515]
> *FUNCTION [RespawnAsTitan()] mp/_base_gametype_mp.gnut line [462]
> 
> [16:39:18] [info] [SERVER SCRIPT] LOCALS
> [soul] NULL
> [fullCopy] true
> [titan] ENTITY (npc_titan [265] (NPC "npc_titan_auto_stryder_sniper" at <-152.918 -547.427 1747.53>))
> [player] ENTITY (player YODIROVANIJ [3] (player "YODIROVANIJ" at <-152.918 -547.427 1747.53>))
> [this] TABLE
> [xyOffset] <43.9989, 0.312859, 520>
> [camera] ENTITY (point_viewcontrol [350] at <-117.91 -574.082 2267.53>)
> [titan] ENTITY (npc_titan [265] (NPC "npc_titan_auto_stryder_sniper" at <-152.918 -547.427 1747.53>))
> [warpAttach] unknown struct
> [model] $"models/titans/light/titan_light_raptor.mdl"
> [titanLoadout] unknown struct
> [spawnpoint] ENTITY (info_spawnpoint_titan info_spawnpoint_titan_10 [0] at <-152.92 -547.43 -127.969>)
> [manualPosition] false
> [player] ENTITY (player YODIROVANIJ [3] (player "YODIROVANIJ" at <-152.918 -547.427 1747.53>))
> [this] TABLE
> 
> DIAGPRINTS
> 
> [16:39:18] [info] [SERVER SPEW_WARNING] point_viewcontrol point_viewcontrol [350] called Disable when it wasn't the players active view entity.
> [16:39:18] [error] Northstar has crashed! a minidump has been written and exception info is available below:
> [16:39:18] [error] Cause: Access Violation
> Attempted to read from: 0x00000000
> [16:39:18] [error] At: engine.dll + 0x247d3a
> [16:39:18] [error]     Northstar.dll + 0x7ffd3b7c9e60
> [16:39:18] [error]     ntdll.dll + 0x7ffda133bfea
> [16:39:18] [error]     ntdll.dll + 0x7ffda12f5812
> [16:39:18] [error]     ntdll.dll + 0x7ffda136730e
> [16:39:18] [error]     engine.dll + 0x7ffc6a7d7d3a
> [16:39:18] [error]     engine.dll + 0x7ffc6a9a7466
> [16:39:18] [error]     engine.dll + 0x7ffc6a6b0c2f
> [16:39:18] [error]     engine.dll + 0x7ffc6a6b0542
> [16:39:18] [error]     engine.dll + 0x7ffc6a6fdb55
> [16:39:18] [error]     engine.dll + 0x7ffc6a7588c0
> [16:39:18] [error]     Northstar.dll + 0x7ffd3b7b18bc
> [16:39:18] [error]     engine.dll + 0x7ffc6a75652f
> [16:39:18] [error]     engine.dll + 0x7ffc6a920e2d
> [16:39:18] [error]     engine.dll + 0x7ffc6a7579d9
> [16:39:18] [error]     engine.dll + 0x7ffc6a75793c
> [16:39:18] [error]     launcher.dll + 0x7ffd41b25afd
> [16:39:18] [error]     launcher.dll + 0x7ffd41b25afd
> [16:39:18] [error]     launcher.dll + 0x7ffd41b1d386
> [16:39:18] [error]     NorthstarLauncher.exe + 0x7ff7b4443bbd
> [16:39:18] [error]     NorthstarLauncher.exe + 0x7ff7b4446d40
> [16:39:18] [error]     KERNEL32.DLL + 0x7ffda0b754e0
> [16:39:18] [error]     ntdll.dll + 0x7ffda12c485b
> [16:39:18] [error] RAX: 0x0
> [16:39:18] [error] RBX: 0x7ffc6ad756d0
> [16:39:18] [error] RCX: 0x0
> [16:39:18] [error] RDX: 0x0
> [16:39:18] [error] RSI: 0x7ffc7d66bb78
> [16:39:18] [error] RDI: 0x7ffc7d66bb78
> [16:39:18] [error] RBP: 0x7ffc7d66bd88
> [16:39:18] [error] RSP: 0x29791af060
> [16:39:18] [error] R8: 0x7ffc7d66bb78
> [16:39:18] [error] R9: 0x65
> [16:39:18] [error] R10: 0x7ffc7d66bd94
> [16:39:18] [error] R11: 0x7ffc6ab978ec
> [16:39:18] [error] R12: 0x0
> [16:39:18] [error] R13: 0x0
> [16:39:18] [error] R14: 0xffffffff
> [16:39:18] [error] R15: 0x1```
> ```

this is also fixed with R2Northstar/NorthstarMods#173

**Comment by abarichello** [comment] 2022-02-21 22:57
You should create a different issue for each error

**Comment by michardy** [comment] 2022-04-10 06:56
Not sure if I should add to this issue due to the number of issues reported or just open a new issue.  I got something similar to the first reported error.

```
[06:43:06] [info] [DEDICATED PRINT] [1554.467]
[06:43:06] [info] [DEDICATED PRINT] FatalError:
[06:43:06] [info] [DEDICATED PRINT] Tried to remove entity #311:npc_titan [311]:models/titans/light/titan_light_ronin_prime.mdl while a player (#8, '_____', lifestate #0) was attached.
Tried to remove entity #311:npc_titan [311]:models/titans/light/titan_light_ronin_prime.mdl while a player (#8, '_____', lifestate #0) was attached.
Error: Failed to run server: server exited: exit status 18.
```

This occurred while ejecting from a doomed titan.  The client view more or less instantly switched to the animation for pulling a battery from an enemy titan.

Server: 1.6.0 (Linux 5.13.0-1023-gcp #28-Ubuntu SMP x86_64)
Client: 1.6.1 (Windows 10 21H2 x86_64)

**Comment by E3VL** [comment] 2022-04-15 20:58
Gamemode Attrition

[nslog2022-04-15 13-46-46.txt](https://github.com/R2Northstar/Northstar/files/8498250/nslog2022-04-15.13-46-46.txt)

**Comment by GeckoEidechse** [comment] 2022-04-16 09:18
As @abarichello said, these should be separate issues, so I'm closing this one. If you find a somewhat reproducible crash, please open a new issue. If not reproducible it's advised to go over Discord instead.

**Closed by GeckoEidechse** 2022-04-16 09:18 UTC
Labels: bug
